Repository MitulSonagara/truth-tunnel, pull requests merged in 2024-10, with the labels that each got.

#4 added logo
  public/assets/logo.png
  public/assets/logo1.png
  public/assets/logo2.png
  src/app/favicon.ico
  src/app/layout.tsx
  src/components/Navbar.tsx
Labels: gssoc, level1

#33 Added the Dockerfile
  .env.sample
  Dockerfile
Labels: level2, hacktoberfest-accepted, gssoc-ext

#35 Added password hide show
  src/app/(auth)/sign-in/page.tsx
  src/app/(auth)/sign-up/page.tsx
Labels: level2, hacktoberfest-accepted, gssoc-ext

#36 Enhance Readme
  README.md
Labels: level1, hacktoberfest-accepted, gssoc-ext

#39 Added PR template
  .github/ISSUE_TEMPLATE/PR_template.md
Labels: level1, hacktoberfest-accepted, gssoc-ext

#41 fix #38 username validation on signup page
  src/app/api/check-username-unique/route.ts
Labels: level2, hacktoberfest-accepted, gssoc-ext

#40 fixes #37: Feature Prisma ORM integration
  README.md
  package-lock.json
  package.json
  prisma/schema.prisma
  src/app/(app)/dashboard/page.tsx
  src/app/api/accept-messages/route.ts
  src/app/api/auth/[...nextauth]/options.ts
  src/app/api/check-username-unique/route.ts
  src/app/api/delete-message/[messageId]/route.ts
  src/app/api/get-messages/route.ts
  src/app/api/send-message/route.ts
  src/app/api/sign-up/route.ts
  src/app/api/verify-code/route.ts
  src/lib/db.ts
  src/types/next-auth.d.ts
Labels: level3, hacktoberfest-accepted, gssoc-ext

#47 Implement Common Loaders and Validation for Authentication Pages
  src/app/(auth)/sign-in/page.tsx
  src/app/(auth)/sign-up/page.tsx
  src/app/(auth)/verify/[username]/page.tsx
  src/app/api/sign-up/route.ts
  src/components/Loader.tsx
Labels: level3, hacktoberfest-accepted, gssoc-ext

#49 feat: theme toggle and light mode
  package-lock.json
  package.json
  src/app/globals.css
  src/app/layout.tsx
  src/components/Navbar.tsx
  src/components/ThemeToggle.tsx
  src/components/ui/dropdown-menu.tsx
  src/context/ThemeProvider.tsx
Labels: level3, hacktoberfest-accepted, gssoc-ext

#51 Added error messages
  src/app/(auth)/sign-up/page.tsx
  src/schemas/signInSchema.ts
Labels: level2, hacktoberfest-accepted, gssoc-ext

#55 Create auto-comment-on-close.yml
  .github/workflow/auto-comment-on-close.yml
Labels: level1, hacktoberfest-accepted, gssoc-ext

#57 Fixed logo for light mode
  src/components/Navbar.tsx
Labels: level1, hacktoberfest-accepted, gssoc-ext

#29 Feature: Added Google Authentication and Updated README and .env.sample Issue Reference: #9
  .env.sample
  package-lock.json
  package.json
  prisma/schema.prisma
  public/google.svg
  src/app/(auth)/sign-in/page.tsx
  src/app/(auth)/sign-up/page.tsx
  src/app/api/accept-messages/route.ts
  src/app/api/auth/[...nextauth]/options.ts
  src/app/api/sign-up/route.ts
  src/app/api/verify-code/route.ts
  src/helpers/sendVerificationEmail.ts
  src/lib/dbConnect.ts
  src/model/User.ts
Labels: level3, hacktoberfest-accepted, gssoc-ext

#64 Modified README.md file & Created LICENSE File for project
  LICENSE
  README.md
Labels: level2, hacktoberfest-accepted, gssoc-ext

#62 Update README.md
  README.md
Labels: level1, hacktoberfest-accepted, gssoc-ext

#66 Fix for Issue #63 - Login Button on Signup Page Returns 404
  src/app/(auth)/sign-up/page.tsx
Labels: level2, hacktoberfest-accepted, gssoc-ext

#70 feat: new UI design
  package-lock.json
  package.json
  src/app/(app)/dashboard/page.tsx
  src/app/(app)/page.tsx
  src/app/u/[username]/page.tsx
  src/app/u/layout.tsx
  src/components/Navbar.tsx
Labels: level3, hacktoberfest-accepted, gssoc-ext

#72 feat: Settings to change username of the user
  package-lock.json
  package.json
  src/app/(app)/dashboard/page.tsx
  src/app/api/auth/[...nextauth]/options.ts
  src/app/api/change-username/route.ts
  src/app/layout.tsx
  src/components/UsernameChangeForm.tsx
  src/components/ui/dialog.tsx
  src/context/AuthProvider.tsx
  src/stores/username-form-store.ts
Labels: level3, hacktoberfest-accepted, gssoc-ext

#75 Feat: Implement Randomly Generated Usernames for Google Sign-In #65
  src/app/api/auth/[...nextauth]/options.ts
  src/helpers/usernameGenerator.ts
Labels: level3, hacktoberfest-accepted, gssoc-ext

#81 added scroll to top
  src/app/(app)/page.tsx
  src/components/ScrollToTopButton.tsx
Labels: level2, hacktoberfest-accepted, gssoc-ext

#77 fixes #74: Feature message encryption
  package-lock.json
  package.json
  prisma/schema.prisma
  src/app/(app)/dashboard/page.tsx
  src/app/api/auth/[...nextauth]/options.ts
  src/app/api/savePublicKey/route.ts
  src/app/api/send-message/route.ts
  src/app/api/sign-up/route.ts
  src/app/layout.tsx
  src/components/EncryptionKeyModal.tsx
  src/components/ui/alert.tsx
  src/components/ui/checkbox.tsx
  src/lib/crypto.ts
  src/stores/encryption-key-modal-store.ts
  src/types/next-auth.d.ts
Labels: level3, hacktoberfest-accepted, gssoc-ext

#96 feat: Add encryption key option
  package.json
  prisma/schema.prisma
  src/app/(app)/dashboard/page.tsx
  src/app/api/check/encryption/route.ts
  src/app/api/savePublicKey/route.ts
  src/app/layout.tsx
  src/components/ChangeEncryptionKeyModal.tsx
  src/components/EncryptionKeyModal.tsx
  src/components/ForgetEncryptionKeyModal.tsx
  src/components/UsernameChangeForm.tsx
  src/context/ModalProvider.tsx
  src/lib/crypto.ts
  src/lib/utils.ts
  src/stores/change-encryption-modal-store.ts
  src/stores/forget-encryption-modal-store.ts
Labels: level3, hacktoberfest-accepted, gssoc-ext

#101 Improve Sign-Up and Sign-In Pages and Navbar for Dark and Light Themes (Fixes #88)
  package-lock.json
  src/app/(auth)/sign-in/page.tsx
  src/app/(auth)/sign-up/page.tsx
  src/components/Navbar.tsx
Labels: level2, hacktoberfest-accepted, gssoc-ext

#110 feat: delete all messages button
  src/app/(app)/dashboard/page.tsx
  src/app/api/messages/delete/[messageId]/route.ts
  src/app/api/messages/delete/route.ts
  src/components/DeletionConfirmModal.tsx
  src/components/EncryptionKeyModal.tsx
  src/context/ModalProvider.tsx
  src/stores/delete-modal-store.ts
Labels: level3, hacktoberfest-accepted, gssoc-ext

#112 Add the color to the forget text in Generate new key
  src/components/ChangeEncryptionKeyModal.tsx
Labels: level1, hacktoberfest-accepted, gssoc-ext

#114 rvamp landing page
  src/app/(app)/page.tsx
Labels: level2, hacktoberfest-accepted, gssoc-ext

#115 Add laoding to the user edit modal change button
  src/components/UsernameChangeForm.tsx
Labels: level2, hacktoberfest-accepted, gssoc-ext

#116 add toaster on login page
  src/app/(auth)/sign-in/page.tsx
Labels: level2, hacktoberfest-accepted, gssoc-ext

#113 Add the navbar to the enhancement, made it sleek and add responsiveness to it
  src/components/Navbar.tsx
Labels: level2, hacktoberfest-accepted, gssoc-ext

#130 Refactor: code quality and react-query
  package-lock.json
  package.json
  src/app/(app)/dashboard/page.tsx
  src/app/(auth)/sign-up/page.tsx
  src/app/api/change/username/route.ts
  src/app/api/check/encryption/route.ts
  src/app/api/check/username/route.ts
  src/app/api/delete-message/[messageId]/route.ts
  src/app/api/messages/accept/route.ts
  src/app/api/messages/route.ts
  src/app/api/messages/send/route.ts
  src/app/api/messages/suggest/route.ts
  src/app/layout.tsx
  src/app/u/[username]/page.tsx
  src/components/ClientSessionProvider.tsx
  src/components/Messages.tsx
  src/components/alerts/add-encryption-alert.tsx
  src/components/alerts/generate-encryption-alert.tsx
  src/components/modals/ChangeEncryptionKeyModal.tsx
  src/components/modals/DeletionConfirmModal.tsx
  src/components/modals/EncryptionKeyModal.tsx
  src/components/modals/ForgetEncryptionKeyModal.tsx
  src/components/modals/UsernameChangeModal.tsx
  src/components/ui/toast.tsx
  src/components/ui/toaster.tsx
  src/components/ui/use-toast.ts
  src/context/ModalProvider.tsx
  src/context/QueryProvider.tsx
  src/hooks/check-encryptionkey.ts
  src/lib/dbConnect.ts
  src/lib/queries.ts
  src/lib/resend.ts
  src/lib/utils.ts
  src/messages.json
  src/model/User.ts
  src/stores/change-encryption-modal-store.ts
  src/stores/encryption-key-modal-store.ts
  src/stores/forget-encryption-modal-store.ts
  src/stores/modals-store.ts
  src/stores/username-form-store.ts
  src/types/ApiResponse.ts
  src/types/default-modal-store.ts
Labels: level3, hacktoberfest-accepted, gssoc-ext

#132 added social icons - follow us
  public/assets/fb.png
  public/assets/insta.png
  public/assets/linkedin.png
  public/assets/youtube.png
  src/app/(app)/page.tsx
Labels: level3, hacktoberfest-accepted, gssoc-ext

#136 Added css property to scroll in modal
  src/components/modals/ForgetEncryptionKeyModal.tsx
Labels: level2, hacktoberfest-accepted, gssoc-ext

#143 feat: uses index DB
  package-lock.json
  package.json
  src/components/Messages.tsx
  src/components/modals/ChangeEncryptionKeyModal.tsx
  src/components/modals/EncryptionKeyModal.tsx
  src/components/modals/ForgetEncryptionKeyModal.tsx
  src/hooks/check-encryptionkey.ts
  src/hooks/use-decrypt-message.ts
  src/lib/indexedDB.ts
  src/lib/utils.ts
Labels: level3, hacktoberfest-accepted, gssoc-ext

#142 Fixes #137: longer loads and other bugs
  package-lock.json
  package.json
  public/assets/logo.svg
  src/app/(app)/dashboard/page.tsx
  src/app/api/messages/route.ts
  src/components/Logo.tsx
  src/components/Navbar.tsx
  src/components/modals/EncryptionKeyModal.tsx
  src/components/modals/ForgetEncryptionKeyModal.tsx
  src/hooks/useProfileUrl.ts
  src/types/comlinkWorkerTypes.ts
  src/workers/crypto.ts
Labels: level2, hacktoberfest-accepted, gssoc-ext

#150 feat: e2e encryption
  src/app/api/messages/send/route.ts
  src/app/u/[username]/page.tsx
  src/components/MessagingForm.tsx
  src/components/ui/badge.tsx
  src/hooks/use-decrypt-message.ts
Labels: level3, hacktoberfest-accepted, gssoc-ext

#135 Added profile drop-down
  public/assets/profile-icon.jpg
  src/app/(app)/page.tsx
  src/components/Navbar.tsx
  src/components/alerts/add-encryption-alert.tsx
Labels: level3, hacktoberfest-accepted, gssoc-ext

#157 Implement GitHub PR Issue Checker Workflow
  .github/workflow/pr-checker.yml
Labels: level2, hacktoberfest-accepted, gssoc-ext

#156 added terms and conditions
  src/app/(app)/page.tsx
  src/app/(app)/terms/page.tsx
  src/app/api/auth/[...nextauth]/options.ts
Labels: level2, hacktoberfest-accepted, gssoc-ext

#120 Fixed navbar on top in Navbar ui
  src/app/(auth)/sign-in/page.tsx
  src/components/Navbar.tsx
Labels: level2, hacktoberfest-accepted, gssoc-ext

#165 feat: top loader page transition
  package-lock.json
  package.json
  src/app/(auth)/forgot-password/email/page.tsx
  src/app/(auth)/forgot-password/otp-verify/[username]/page.tsx
  src/app/(auth)/forgot-password/reset-password/[username]/page.tsx
  src/app/(auth)/sign-in/page.tsx
  src/app/(auth)/sign-up/page.tsx
  src/app/(auth)/verify/[username]/page.tsx
  src/app/layout.tsx
  src/components/modals/DeletionConfirmModal.tsx
Labels: level3, hacktoberfest-accepted, gssoc-ext

#167 Image added and changed UI respectively
  package-lock.json
  public/assets/secret.webp
  src/app/(app)/page.tsx
  tailwind.config.ts
Labels: level2, hacktoberfest-accepted, gssoc-ext

#168 Fixes #162: Sign In Page Layout for Mobile View
  src/app/(auth)/sign-in/page.tsx
Labels: level1, hacktoberfest-accepted, gssoc-ext

#161 Add Navigation Path to 'Send Message' Page & Fix Application Error (fixes #144, #159)
  src/app/(app)/dashboard/page.tsx
  src/app/api/search/[username]/route.ts
  src/components/search.tsx
Labels: level3, hacktoberfest-accepted, gssoc-ext

#174 Fix alignment
  src/app/(auth)/verify/[username]/page.tsx
Labels: level1, hacktoberfest-accepted, gssoc-ext

#182 Fix DARK mode in advance convert features section
  .env.example
  package-lock.json
  src/app/(app)/page.tsx
Labels: level1, hacktoberfest-accepted, gssoc-ext

#183 feat: search users sheet with suggested users
  package-lock.json
  package.json
  src/app/(app)/dashboard/page.tsx
  src/app/api/search/[username]/route.ts
  src/app/api/search/route.ts
  src/components/Navbar.tsx
  src/components/search.tsx
  src/components/sheets/SearchUserSheet.tsx
  src/components/ui/avatar.tsx
  src/components/ui/scroll-area.tsx
  src/components/ui/sheet.tsx
  src/context/ModalProvider.tsx
  src/lib/queries.ts
  src/stores/sheets-store.ts
  src/types/ApiResponse.ts
Labels: level3, hacktoberfest-accepted, gssoc-ext

#185 GitHub icon add
  package-lock.json
  package.json
  src/components/Navbar.tsx
Labels: level1, hacktoberfest-accepted, gssoc-ext

#172 Add about page
  src/app/(app)/about/page.tsx
Labels: level2, hacktoberfest-accepted, gssoc-ext

#117 Add git contributros page
  next.config.mjs
  src/app/(app)/contributors/page.tsx
Labels: level3, hacktoberfest-accepted, gssoc-ext

#189 changed login message
  src/schemas/signInSchema.ts
Labels: level2, hacktoberfest-accepted, gssoc-ext

#173 Add contact us page
  package-lock.json
  src/app/(app)/contactus/page.tsx
Labels: level2, hacktoberfest-accepted, gssoc-ext

#188 Added strong password validation in zod file
  src/app/(app)/page.tsx
  src/app/(auth)/sign-up/page.tsx
  src/schemas/signUpSchema.ts
Labels: level2, hacktoberfest-accepted, gssoc-ext

#196 Added toast message for login failure
  src/app/(auth)/sign-in/page.tsx
Labels: level1, hacktoberfest-accepted, gssoc-ext

#216 Major UI Fixes
  package-lock.json
  package.json
  src/app/(app)/about/page.tsx
  src/app/(app)/contributors/page.tsx
  src/components/Navbar.tsx
Labels: level3, hacktoberfest-accepted, gssoc-ext

#211 Handle invalid username error in backend to prevent crash
  src/app/api/search/route.ts
Labels: level2, hacktoberfest-accepted, gssoc-ext

#209 Added debounce query in search bar
  src/app/api/search/route.ts
  src/components/sheets/SearchUserSheet.tsx
Labels: level2, hacktoberfest-accepted, gssoc-ext

#224 Successfully Updated CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: level1, hacktoberfest-accepted, gssoc-ext

#240 Add New line feature and fix input field clear on send message
  src/components/MessagingForm.tsx
Labels: level2, hacktoberfest-accepted, gssoc-ext

#212 minor ui fixes
  package-lock.json
  src/app/(app)/page.tsx
  src/components/Navbar.tsx
Labels: level1, hacktoberfest-accepted, gssoc-ext

#241 Fix Delete operation on Single Message | ADD loader to trash icon
  src/components/Messages.tsx
Labels: level2, hacktoberfest-accepted, gssoc-ext

#243 Fix inifinite loop of decrypt messages
  src/components/modals/EncryptionKeyModal.tsx
  src/hooks/use-decrypt-message.ts
  src/lib/crypto.ts
  src/lib/queries.ts
Labels: level2, hacktoberfest-accepted, gssoc-ext

#249 🛠️FIX : Contact Us form Name validation
  src/app/(app)/contactus/page.tsx
Labels: level1, hacktoberfest-accepted, gssoc-ext

#225 added chatbot to the website
  src/app/layout.tsx
  src/components/ScrollToTopButton.tsx
Labels: level3, hacktoberfest-accepted, gssoc-ext

#184 fix: auto generate encryption keys if user do not have
  prisma/schema.prisma
  src/app/(app)/dashboard/page.tsx
  src/app/(auth)/sign-in/page.tsx
  src/app/layout.tsx
  src/components/Navbar.tsx
  src/helpers/checkAndSaveKeys.ts
Labels: level2, hacktoberfest-accepted, gssoc-ext

#253 Added Table to Display Repository Statistics in README.md
  README.md
Labels: level1, hacktoberfest-accepted, gssoc-ext

#218 ContactUs Page Enhanced
  package.json
  src/app/(app)/contactus/page.tsx
Labels: level2, hacktoberfest-accepted, gssoc-ext

#259 Feat/better contributors page with responsiveness
  package-lock.json
  src/app/(app)/contributors/page.tsx
  src/components/contributorCard.tsx
Labels: level2, hacktoberfest-accepted, gssoc-ext

#278 added dedicated faq section and help center
  package-lock.json
  src/app/(app)/page.tsx
  src/app/faq/page.tsx
  src/app/help/[topic]/page.tsx
  src/app/help/layout.tsx
  src/app/help/page.tsx
  src/components/Navbar.tsx
Labels: level2, hacktoberfest-accepted, gssoc-ext

#271 Added testimonial
  public/assets/profilePic.jpg
  src/app/(app)/page.tsx
  src/components/Testimonial.tsx
Labels: level2, hacktoberfest-accepted, gssoc-ext

#280 add toggle to switch between modes
  src/components/ThemeToggle.tsx
Labels: level1, hacktoberfest-accepted, gssoc-ext

#272 Error 404 page
  package-lock.json
  src/app/images/logo.png
  src/app/images/logo2.png
  src/app/not-found.tsx
Labels: level2, hacktoberfest-accepted, gssoc-ext

#285 Implement Issue Reminder Workflow🚀
  .github/workflow/issue-reminder.yml
Labels: level1, hacktoberfest-accepted, gssoc-ext

#286 Adding a Workflow for greetings to new issue
  .github/workflow/issue-open-greet.yml
Labels: level1, hacktoberfest-accepted, gssoc-ext

#289 Add GitHub Workflow for Auto-Closing Similar Issue Requests
  .github/workflow/detect-duplicate.yml
Labels: level1, hacktoberfest-accepted, gssoc-ext

#294 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: level1, hacktoberfest-accepted, gssoc-ext

#293 Enhanced the ui of tems of use page
  src/app/(app)/page.tsx
  src/app/(app)/terms/page.tsx
Labels: level2, hacktoberfest-accepted, gssoc-ext
